##
## EPITECH PROJECT, 2025
## Makefile
## File description:
## Makefile
##

SRC	=	*.c

OBJ	=	$(SRC:.c=.o)

NAME	=	test

all:	$(NAME)

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re:	fclean all
